name: test

on: [push]

# on:
#   workflow_dispatch:
#     inputs:
#       version-suffix:
#         description: "Informe um sufixo para identificar a versão:"
#         type: string
#         default: "test"
#         required: true
#   push:
#     branches: ["release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      hardening: "Dexguard" # values are "Dexguard" or "Normal"
    steps:
      - name: step1
        run: |
          echo "testvar1 ${testvar1}"
          echo "testvar2 ${testvar2}"
          testvar1="change1"
          testvar2="change2"
          echo "testvar1=$testvar1" >> $GITHUB_OUTPUT
          echo "testvar2=$testvar2" >> $GITHUB_OUTPUT

      - name: step2
        run: |
          echo "testvar1 ${{ steps.step1.outputs.testvar1 }}"
          echo "testvar2 ${{ steps.step1.outputs.testvar2 }}"
      
          ./gradlew aaaaa

      
