name: test

on: [push]

# on:
#   workflow_dispatch:
#     inputs:
#       version-suffix:
#         description: "Informe um sufixo para identificar a versão:"
#         type: string
#         default: "test"
#         required: true
#   push:
#     branches: ["release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      hardening: "Dexguard" # values are "Dexguard" or "Normal"
    steps:
      - name: step 1
        id: step1
        run: |
          echo "testvar1 ${testvar1}"
          echo "testvar2 ${testvar2}"
          testvar1="change1"
          testvar2="change2"
          testvar2="change3"
          under_score="value ok"

          if [ $testvar1 = "change1" ]; then
            testvar2="asdf"
          fi

          echo "testvar1=$testvar1" >> $GITHUB_OUTPUT
          echo "testvar2=$testvar2" >> $GITHUB_OUTPUT
          echo "under_score=$under_score" >> $GITHUB_OUTPUT
          echo "GITHUB_OUTPUT: "
          cat $GITHUB_OUTPUT

      - name: step 2
        id: step2
        env:
          var1: ${{ steps.step1.outputs.testvar1 }}
          var2: ${{ steps.step1.outputs.testvar2 }}
          var_underscore: ${{ steps.step1.outputs.under_score }}
        run: |
          echo "tv1 : ${{ steps.step1.outputs.testvar1 }}"
          echo "tv2 : ${{ steps.step1.outputs.testvar2 }}"
          echo "testvar1: $var1"
          echo "testvar2: $var2"
          echo "testvar1: ${var1}"
          echo "testvar2: ${var2}"
          echo "var_underscore: $var_underscore"
          
          apk_input="testteapk"
          echo "apk_input=$apk_input" >> $GITHUB_OUTPUT
      
          
      - name: aux action
        uses: DanielScapin/test-aux-action@main
        env:
          apk_input: ${{ steps.step2.outputs.apk_input }}

        with:
          input: "app/build/outputs/apk/stage${{ env.hardening }}/release/${{ env.apk_input }}"
          output: "app/build/outputs/apk/stage${hardening}/release/app-stage-release-signed.apk"
      
