name: test

on: [push]

# on:
#   workflow_dispatch:
#     inputs:
#       version-suffix:
#         description: "Informe um sufixo para identificar a versão:"
#         type: string
#         default: "test"
#         required: true
#   push:
#     branches: ["release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      hardening: "Dexguard" # values are "Dexguard" or "Normal"
      testvar1:
      testvar2: 
    steps:
      - name: ttttt
        run: |
          echo "testvar1 ${testvar1}"
          echo "testvar2 ${testvar2}"
          testvar1="change1"
          testvar2="change2"

      - name: t2
        run: |
          echo "testvar1 ${testvar1}"
          echo "testvar2 ${testvar2}"
      
          ./gradlew aaaaa

      
